// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR1dGRMxDdv4qS6XuaMuKe7CP5R4T7KnA',
    appId: '1:522335943318:web:ac730254ddd27c5f04a0b7',
    messagingSenderId: '522335943318',
    projectId: 'bloomcycle-56556',
    authDomain: 'bloomcycle-56556.firebaseapp.com',
    storageBucket: 'bloomcycle-56556.firebasestorage.app',
    measurementId: 'G-RTEGKQDGNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJC8KBQL_1urfBiuJXDcJZ7y6zb-riQI8',
    appId: '1:522335943318:android:1f2d42a3aba34e0404a0b7',
    messagingSenderId: '522335943318',
    projectId: 'bloomcycle-56556',
    storageBucket: 'bloomcycle-56556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjeglx2xy_2z3muhaOQ3QwetQ4ksJPB9g',
    appId: '1:522335943318:ios:bfea7a1e251c8dc604a0b7',
    messagingSenderId: '522335943318',
    projectId: 'bloomcycle-56556',
    storageBucket: 'bloomcycle-56556.firebasestorage.app',
    iosClientId: '522335943318-shd2obs5hh9g1bnpuj0qvpjj40q1bfo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloomcycle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjeglx2xy_2z3muhaOQ3QwetQ4ksJPB9g',
    appId: '1:522335943318:ios:bfea7a1e251c8dc604a0b7',
    messagingSenderId: '522335943318',
    projectId: 'bloomcycle-56556',
    storageBucket: 'bloomcycle-56556.firebasestorage.app',
    iosClientId: '522335943318-shd2obs5hh9g1bnpuj0qvpjj40q1bfo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloomcycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR1dGRMxDdv4qS6XuaMuKe7CP5R4T7KnA',
    appId: '1:522335943318:web:95e9542ea1922ee404a0b7',
    messagingSenderId: '522335943318',
    projectId: 'bloomcycle-56556',
    authDomain: 'bloomcycle-56556.firebaseapp.com',
    storageBucket: 'bloomcycle-56556.firebasestorage.app',
    measurementId: 'G-W1WM9XPF83',
  );
}
